export const BRAND = {
  name: "Network Capital",
  slogan: "Emprendé con estilo",
  subtitle: "Venta por mayor · Hecho en Uruguay",
  address: "Pedro Bustamante 1500, Montevideo, Uruguay",
  mapsUrl: "https://maps.google.com/?q=Pedro+Bustamante+1500+Montevideo+Uruguay",
  whatsapp: "59891358992",
  phone: "+598 91 358 992",
  email: "networkcapital@quotixos.com",
  instagram: "@networkcapital.uy",
  ctaUrl: "https://app-networkcapital.quotixos.com",
  minOrder: 10,
  productionDays: 7,
  depositPercent: 50,
  designFixPrice: 300,
  xxlSurcharge: 30,
  colors: {
    yellow: "#F2B411",
    blue: "#007DB8",
    pink: "#E91E8C",
    navy: "#0B1628",
    dark: "#0A0A0A",
    cream: "#F5F5F0",
    white: "#FFFFFF",
  },
};

export interface PriceTier {
  qty: number;
  label: string;
  price: number;
}

export interface SizeRow {
  size: string;
  largo?: number;
  ancho?: number;
  manga?: number;
}

export interface Product {
  id: string;
  name: string;
  category: string;
  priceFrom: number;
  image: string;
  description: string;
  features: string[];
  colors: string[];
  minQty: number;
  weight: string;
  composition: string;
  sizes: string[];
  sizeTable: SizeRow[];
  priceWithPrint: PriceTier[];
  priceWithoutPrint: PriceTier[];
  stampIdeas?: string[];
  details?: string[];
}

// ─── Remeras ───
const REMERA_SIZES = ["S", "M", "L", "XL", "XXL", "XXXL"];
const REMERA_SIZE_TABLE: SizeRow[] = [
  { size: "S", largo: 70, ancho: 46 },
  { size: "M", largo: 73, ancho: 51 },
  { size: "L", largo: 76, ancho: 56 },
  { size: "XL", largo: 78, ancho: 61 },
  { size: "XXL", largo: 81, ancho: 66 },
  { size: "XXXL", largo: 83, ancho: 71 },
];

const REMERA_STONE_WASH_PRICE_WITH: PriceTier[] = [
  { qty: 10, label: "10+", price: 370 },
  { qty: 20, label: "20+", price: 350 },
  { qty: 30, label: "30+", price: 330 },
];
const REMERA_STONE_WASH_PRICE_WITHOUT: PriceTier[] = [
  { qty: 10, label: "10+", price: 270 },
  { qty: 20, label: "20+", price: 240 },
  { qty: 30, label: "30+", price: 220 },
];

const REMERA_OVERSIZE_PRICE_WITH: PriceTier[] = [
  { qty: 10, label: "10+", price: 390 },
  { qty: 20, label: "20+", price: 370 },
  { qty: 30, label: "30+", price: 350 },
];
const REMERA_OVERSIZE_PRICE_WITHOUT: PriceTier[] = [
  { qty: 10, label: "10+", price: 290 },
  { qty: 20, label: "20+", price: 270 },
  { qty: 30, label: "30+", price: 250 },
];

// ─── Buzos ───
const BUZO_SIZES = ["S", "M", "L", "XL", "XXL"];
const BUZO_SIZE_TABLE: SizeRow[] = [
  { size: "S", largo: 66, ancho: 52, manga: 58 },
  { size: "M", largo: 69, ancho: 56, manga: 60 },
  { size: "L", largo: 72, ancho: 60, manga: 62 },
  { size: "XL", largo: 75, ancho: 64, manga: 64 },
  { size: "XXL", largo: 78, ancho: 68, manga: 66 },
];

const BUZO_PRICE_WITH: PriceTier[] = [
  { qty: 10, label: "10+", price: 590 },
  { qty: 20, label: "20+", price: 560 },
  { qty: 30, label: "30+", price: 530 },
];
const BUZO_PRICE_WITHOUT: PriceTier[] = [
  { qty: 10, label: "10+", price: 490 },
  { qty: 20, label: "20+", price: 460 },
  { qty: 30, label: "30+", price: 430 },
];

// ─── Camperas ───
const CAMPERA_SIZES = ["S", "M", "L", "XL", "XXL"];
const CAMPERA_SIZE_TABLE: SizeRow[] = [
  { size: "S", largo: 68, ancho: 54, manga: 60 },
  { size: "M", largo: 71, ancho: 58, manga: 62 },
  { size: "L", largo: 74, ancho: 62, manga: 64 },
  { size: "XL", largo: 77, ancho: 66, manga: 66 },
  { size: "XXL", largo: 80, ancho: 70, manga: 68 },
];

const CAMPERA_PRICE_WITH: PriceTier[] = [
  { qty: 10, label: "10+", price: 890 },
  { qty: 20, label: "20+", price: 850 },
  { qty: 30, label: "30+", price: 820 },
];
const CAMPERA_PRICE_WITHOUT: PriceTier[] = [
  { qty: 10, label: "10+", price: 790 },
  { qty: 20, label: "20+", price: 750 },
  { qty: 30, label: "30+", price: 720 },
];

// ─── Canguros ───
const CANGURO_SIZES = ["S", "M", "L", "XL", "XXL"];
const CANGURO_SIZE_TABLE: SizeRow[] = [
  { size: "S", largo: 66, ancho: 52, manga: 58 },
  { size: "M", largo: 69, ancho: 56, manga: 60 },
  { size: "L", largo: 72, ancho: 60, manga: 62 },
  { size: "XL", largo: 75, ancho: 64, manga: 64 },
  { size: "XXL", largo: 78, ancho: 68, manga: 66 },
];

const CANGURO_PRICE_WITH: PriceTier[] = [
  { qty: 10, label: "10+", price: 590 },
  { qty: 20, label: "20+", price: 560 },
  { qty: 30, label: "30+", price: 530 },
];
const CANGURO_PRICE_WITHOUT: PriceTier[] = [
  { qty: 10, label: "10+", price: 490 },
  { qty: 20, label: "20+", price: 460 },
  { qty: 30, label: "30+", price: 430 },
];

export const PRODUCTS: Product[] = [
  // ─────────────────────────── REMERAS ───────────────────────────
  {
    id: "remera-stonewash-negro",
    name: "Remera Stone Wash Negro",
    category: "Remeras",
    priceFrom: 270,
    image: "/networkcapital/productos/remera stone wash negro.jpeg",
    description: "Remera stone wash en color negro. Corte clásico, ideal para estampar y revender. Acabado premium.",
    features: ["100% algodón", "Stone wash", "Corte clásico", "Ideal para estampar"],
    colors: ["Negro"],
    minQty: 10,
    weight: "180g",
    composition: "100% algodón",
    sizes: REMERA_SIZES,
    sizeTable: REMERA_SIZE_TABLE,
    priceWithPrint: REMERA_STONE_WASH_PRICE_WITH,
    priceWithoutPrint: REMERA_STONE_WASH_PRICE_WITHOUT,
  },
  {
    id: "remera-stonewash-gris-hombre",
    name: "Remera Stone Wash Gris Hombre",
    category: "Remeras",
    priceFrom: 270,
    image: "/networkcapital/productos/remera stone wash gris-hombre.jpeg",
    description: "Remera stone wash en color gris. Corte clásico hombre, ideal para estampar y revender.",
    features: ["100% algodón", "Stone wash", "Corte clásico", "Ideal para estampar"],
    colors: ["Gris"],
    minQty: 10,
    weight: "180g",
    composition: "100% algodón",
    sizes: REMERA_SIZES,
    sizeTable: REMERA_SIZE_TABLE,
    priceWithPrint: REMERA_STONE_WASH_PRICE_WITH,
    priceWithoutPrint: REMERA_STONE_WASH_PRICE_WITHOUT,
  },
  {
    id: "remera-stonewash-gris-mujer",
    name: "Remera Stone Wash Gris Mujer",
    category: "Remeras",
    priceFrom: 270,
    image: "/networkcapital/productos/remera stone wash gris - mujer.jpeg",
    description: "Remera stone wash en color gris. Corte clásico mujer, ideal para estampar y revender.",
    features: ["100% algodón", "Stone wash", "Corte clásico", "Ideal para estampar"],
    colors: ["Gris"],
    minQty: 10,
    weight: "180g",
    composition: "100% algodón",
    sizes: REMERA_SIZES,
    sizeTable: REMERA_SIZE_TABLE,
    priceWithPrint: REMERA_STONE_WASH_PRICE_WITH,
    priceWithoutPrint: REMERA_STONE_WASH_PRICE_WITHOUT,
  },
  {
    id: "remera-stonewash-verde-hombre",
    name: "Remera Stone Wash Verde Hombre",
    category: "Remeras",
    priceFrom: 270,
    image: "/networkcapital/productos/remera stone wash verde-hombre.jpeg",
    description: "Remera stone wash en color verde. Corte clásico hombre, ideal para estampar y revender.",
    features: ["100% algodón", "Stone wash", "Corte clásico", "Ideal para estampar"],
    colors: ["Verde"],
    minQty: 10,
    weight: "180g",
    composition: "100% algodón",
    sizes: REMERA_SIZES,
    sizeTable: REMERA_SIZE_TABLE,
    priceWithPrint: REMERA_STONE_WASH_PRICE_WITH,
    priceWithoutPrint: REMERA_STONE_WASH_PRICE_WITHOUT,
  },
  {
    id: "remera-stonewash-verde-mujer",
    name: "Remera Stone Wash Verde Mujer",
    category: "Remeras",
    priceFrom: 270,
    image: "/networkcapital/productos/remera stone wash verde-mujer.jpeg",
    description: "Remera stone wash en color verde. Corte clásico mujer, ideal para estampar y revender.",
    features: ["100% algodón", "Stone wash", "Corte clásico", "Ideal para estampar"],
    colors: ["Verde"],
    minQty: 10,
    weight: "180g",
    composition: "100% algodón",
    sizes: REMERA_SIZES,
    sizeTable: REMERA_SIZE_TABLE,
    priceWithPrint: REMERA_STONE_WASH_PRICE_WITH,
    priceWithoutPrint: REMERA_STONE_WASH_PRICE_WITHOUT,
  },
  {
    id: "remera-stonewash-marron",
    name: "Remera Stone Wash Marrón",
    category: "Remeras",
    priceFrom: 270,
    image: "/networkcapital/productos/remera marron stone wash.jpeg",
    description: "Remera stone wash en color marrón. Corte clásico, ideal para estampar y revender.",
    features: ["100% algodón", "Stone wash", "Corte clásico", "Ideal para estampar"],
    colors: ["Marrón"],
    minQty: 10,
    weight: "180g",
    composition: "100% algodón",
    sizes: REMERA_SIZES,
    sizeTable: REMERA_SIZE_TABLE,
    priceWithPrint: REMERA_STONE_WASH_PRICE_WITH,
    priceWithoutPrint: REMERA_STONE_WASH_PRICE_WITHOUT,
  },
  {
    id: "remera-oversize-arena-mujer",
    name: "Remera Oversize Arena Mujer",
    category: "Remeras",
    priceFrom: 350,
    image: "/networkcapital/productos/remera oversize arena mujer.png",
    description: "Remera oversize en color arena, corte mujer. Estilo amplio y moderno, perfecta para estampados grandes.",
    features: ["100% algodón", "Corte oversize", "Estilo moderno", "Ideal para estampar"],
    colors: ["Arena"],
    minQty: 10,
    weight: "200g",
    composition: "100% algodón",
    sizes: REMERA_SIZES,
    sizeTable: REMERA_SIZE_TABLE,
    priceWithPrint: REMERA_OVERSIZE_PRICE_WITH,
    priceWithoutPrint: REMERA_OVERSIZE_PRICE_WITHOUT,
  },
  {
    id: "remera-oversize-blanco-mujer",
    name: "Remera Oversize Blanco Mujer",
    category: "Remeras",
    priceFrom: 350,
    image: "/networkcapital/productos/remera oversize blanco mujer.png",
    description: "Remera oversize en color blanco, corte mujer. Estilo amplio y moderno, perfecta para estampados grandes.",
    features: ["100% algodón", "Corte oversize", "Estilo moderno", "Ideal para estampar"],
    colors: ["Blanco"],
    minQty: 10,
    weight: "200g",
    composition: "100% algodón",
    sizes: REMERA_SIZES,
    sizeTable: REMERA_SIZE_TABLE,
    priceWithPrint: REMERA_OVERSIZE_PRICE_WITH,
    priceWithoutPrint: REMERA_OVERSIZE_PRICE_WITHOUT,
  },
  {
    id: "remera-oversize-negro-mujer",
    name: "Remera Oversize Negro Mujer",
    category: "Remeras",
    priceFrom: 350,
    image: "/networkcapital/productos/remera oversize negro mujer.png",
    description: "Remera oversize en color negro, corte mujer. Estilo amplio y moderno, perfecta para estampados grandes.",
    features: ["100% algodón", "Corte oversize", "Estilo moderno", "Ideal para estampar"],
    colors: ["Negro"],
    minQty: 10,
    weight: "200g",
    composition: "100% algodón",
    sizes: REMERA_SIZES,
    sizeTable: REMERA_SIZE_TABLE,
    priceWithPrint: REMERA_OVERSIZE_PRICE_WITH,
    priceWithoutPrint: REMERA_OVERSIZE_PRICE_WITHOUT,
  },
  {
    id: "remera-stonewash-gris",
    name: "Remera Stone Wash Gris",
    category: "Remeras",
    priceFrom: 270,
    image: "/networkcapital/productos/remera stone wash gris.png",
    description: "Remera stone wash en color gris. Corte clásico, ideal para estampar y revender.",
    features: ["100% algodón", "Stone wash", "Corte clásico", "Ideal para estampar"],
    colors: ["Gris"],
    minQty: 10,
    weight: "180g",
    composition: "100% algodón",
    sizes: REMERA_SIZES,
    sizeTable: REMERA_SIZE_TABLE,
    priceWithPrint: REMERA_STONE_WASH_PRICE_WITH,
    priceWithoutPrint: REMERA_STONE_WASH_PRICE_WITHOUT,
  },

  // ─────────────────────────── BUZOS ───────────────────────────
  {
    id: "buzo-medio-cierre-azul",
    name: "Buzo Medio Cierre Azul",
    category: "Buzos",
    priceFrom: 490,
    image: "/networkcapital/productos/buzo medio cierre azul.jpeg",
    description: "Buzo medio cierre en color azul. Cálido, cómodo y perfecto para personalizar con estampado o bordado.",
    features: ["Algodón peinado", "Cierre medio", "Cálido y cómodo", "Ideal para estampar"],
    colors: ["Azul"],
    minQty: 10,
    weight: "280g",
    composition: "80% algodón · 20% poliéster",
    sizes: BUZO_SIZES,
    sizeTable: BUZO_SIZE_TABLE,
    priceWithPrint: BUZO_PRICE_WITH,
    priceWithoutPrint: BUZO_PRICE_WITHOUT,
  },
  {
    id: "buzo-medio-cierre-gris",
    name: "Buzo Medio Cierre Gris",
    category: "Buzos",
    priceFrom: 490,
    image: "/networkcapital/productos/buzo medio cierre gris.jpeg",
    description: "Buzo medio cierre en color gris. Cálido, cómodo y perfecto para personalizar con estampado o bordado.",
    features: ["Algodón peinado", "Cierre medio", "Cálido y cómodo", "Ideal para estampar"],
    colors: ["Gris"],
    minQty: 10,
    weight: "280g",
    composition: "80% algodón · 20% poliéster",
    sizes: BUZO_SIZES,
    sizeTable: BUZO_SIZE_TABLE,
    priceWithPrint: BUZO_PRICE_WITH,
    priceWithoutPrint: BUZO_PRICE_WITHOUT,
  },
  {
    id: "buzo-medio-cierre-negro",
    name: "Buzo Medio Cierre Negro",
    category: "Buzos",
    priceFrom: 490,
    image: "/networkcapital/productos/buzo medio cierre negro.jpeg",
    description: "Buzo medio cierre en color negro. Cálido, cómodo y perfecto para personalizar con estampado o bordado.",
    features: ["Algodón peinado", "Cierre medio", "Cálido y cómodo", "Ideal para estampar"],
    colors: ["Negro"],
    minQty: 10,
    weight: "280g",
    composition: "80% algodón · 20% poliéster",
    sizes: BUZO_SIZES,
    sizeTable: BUZO_SIZE_TABLE,
    priceWithPrint: BUZO_PRICE_WITH,
    priceWithoutPrint: BUZO_PRICE_WITHOUT,
  },

  // ─────────────────────────── CAMPERAS ───────────────────────────
  {
    id: "campera-capitoneada-negra",
    name: "Campera Capitoneada Negra",
    category: "Camperas",
    priceFrom: 790,
    image: "/networkcapital/productos/campera capitoneada negro.jpeg",
    description: "Campera capitoneada en color negro. Abrigo ideal para personalizar con bordado o estampado. Calidad premium.",
    features: ["Capitoneada", "Abrigada", "Corte clásico", "Ideal para bordar"],
    colors: ["Negro"],
    minQty: 10,
    weight: "350g",
    composition: "100% poliéster",
    sizes: CAMPERA_SIZES,
    sizeTable: CAMPERA_SIZE_TABLE,
    priceWithPrint: CAMPERA_PRICE_WITH,
    priceWithoutPrint: CAMPERA_PRICE_WITHOUT,
  },
  {
    id: "campera-neopreno-negra-hombre",
    name: "Campera Neopreno Negra Hombre",
    category: "Camperas",
    priceFrom: 790,
    image: "/networkcapital/productos/campera de neopreno negro.jpeg",
    description: "Campera de neopreno en color negro, corte hombre. Moderna, abrigada y perfecta para personalizar.",
    features: ["Neopreno", "Abrigada", "Corte moderno", "Ideal para estampar"],
    colors: ["Negro"],
    minQty: 10,
    weight: "400g",
    composition: "Neopreno",
    sizes: CAMPERA_SIZES,
    sizeTable: CAMPERA_SIZE_TABLE,
    priceWithPrint: CAMPERA_PRICE_WITH,
    priceWithoutPrint: CAMPERA_PRICE_WITHOUT,
  },
  {
    id: "campera-neopreno-negra-mujer",
    name: "Campera Neopreno Negra Mujer",
    category: "Camperas",
    priceFrom: 790,
    image: "/networkcapital/productos/campera neopreno negro mujer.jpeg",
    description: "Campera de neopreno en color negro, corte mujer. Moderna, abrigada y perfecta para personalizar.",
    features: ["Neopreno", "Abrigada", "Corte mujer", "Ideal para estampar"],
    colors: ["Negro"],
    minQty: 10,
    weight: "400g",
    composition: "Neopreno",
    sizes: CAMPERA_SIZES,
    sizeTable: CAMPERA_SIZE_TABLE,
    priceWithPrint: CAMPERA_PRICE_WITH,
    priceWithoutPrint: CAMPERA_PRICE_WITHOUT,
  },

  // ─────────────────────────── CANGUROS ───────────────────────────
  {
    id: "canguro-clasico-arena",
    name: "Canguro Clásico Arena",
    category: "Canguros",
    priceFrom: 490,
    image: "/networkcapital/productos/canguro clasico arena.jpeg",
    description: "Canguro clásico en color arena. Cómodo, con bolsillo delantero y capucha. Ideal para estampar.",
    features: ["Bolsillo delantero", "Capucha", "Cálido", "Ideal para estampar"],
    colors: ["Arena"],
    minQty: 10,
    weight: "280g",
    composition: "80% algodón · 20% poliéster",
    sizes: CANGURO_SIZES,
    sizeTable: CANGURO_SIZE_TABLE,
    priceWithPrint: CANGURO_PRICE_WITH,
    priceWithoutPrint: CANGURO_PRICE_WITHOUT,
  },
  {
    id: "canguro-clasico-azul-hombre",
    name: "Canguro Clásico Azul Hombre",
    category: "Canguros",
    priceFrom: 490,
    image: "/networkcapital/productos/canguro clasico azul hombre.jpeg",
    description: "Canguro clásico en color azul, corte hombre. Cómodo, con bolsillo delantero y capucha. Ideal para estampar.",
    features: ["Bolsillo delantero", "Capucha", "Cálido", "Ideal para estampar"],
    colors: ["Azul"],
    minQty: 10,
    weight: "280g",
    composition: "80% algodón · 20% poliéster",
    sizes: CANGURO_SIZES,
    sizeTable: CANGURO_SIZE_TABLE,
    priceWithPrint: CANGURO_PRICE_WITH,
    priceWithoutPrint: CANGURO_PRICE_WITHOUT,
  },
  {
    id: "canguro-clasico-francia",
    name: "Canguro Clásico Francia",
    category: "Canguros",
    priceFrom: 490,
    image: "/networkcapital/productos/canguro clasico francia.jpeg",
    description: "Canguro clásico en color Francia (azul Francia). Cómodo, con bolsillo delantero y capucha. Ideal para estampar.",
    features: ["Bolsillo delantero", "Capucha", "Cálido", "Ideal para estampar"],
    colors: ["Francia"],
    minQty: 10,
    weight: "280g",
    composition: "80% algodón · 20% poliéster",
    sizes: CANGURO_SIZES,
    sizeTable: CANGURO_SIZE_TABLE,
    priceWithPrint: CANGURO_PRICE_WITH,
    priceWithoutPrint: CANGURO_PRICE_WITHOUT,
  },
  {
    id: "canguro-clasico-negro",
    name: "Canguro Clásico Negro",
    category: "Canguros",
    priceFrom: 490,
    image: "/networkcapital/productos/canguro clasico negro.jpeg",
    description: "Canguro clásico en color negro. Cómodo, con bolsillo delantero y capucha. Ideal para estampar.",
    features: ["Bolsillo delantero", "Capucha", "Cálido", "Ideal para estampar"],
    colors: ["Negro"],
    minQty: 10,
    weight: "280g",
    composition: "80% algodón · 20% poliéster",
    sizes: CANGURO_SIZES,
    sizeTable: CANGURO_SIZE_TABLE,
    priceWithPrint: CANGURO_PRICE_WITH,
    priceWithoutPrint: CANGURO_PRICE_WITHOUT,
  },
  {
    id: "canguro-clasico-rosa-pastel",
    name: "Canguro Clásico Rosa Pastel",
    category: "Canguros",
    priceFrom: 490,
    image: "/networkcapital/productos/canguro clasico rosa pastel.jpeg",
    description: "Canguro clásico en color rosa pastel. Cómodo, con bolsillo delantero y capucha. Ideal para estampar.",
    features: ["Bolsillo delantero", "Capucha", "Cálido", "Ideal para estampar"],
    colors: ["Rosa Pastel"],
    minQty: 10,
    weight: "280g",
    composition: "80% algodón · 20% poliéster",
    sizes: CANGURO_SIZES,
    sizeTable: CANGURO_SIZE_TABLE,
    priceWithPrint: CANGURO_PRICE_WITH,
    priceWithoutPrint: CANGURO_PRICE_WITHOUT,
  },
  {
    id: "canguro-clasico-verde-bosque",
    name: "Canguro Clásico Verde Bosque",
    category: "Canguros",
    priceFrom: 490,
    image: "/networkcapital/productos/canguro clasico verde bosque.jpeg",
    description: "Canguro clásico en color verde bosque. Cómodo, con bolsillo delantero y capucha. Ideal para estampar.",
    features: ["Bolsillo delantero", "Capucha", "Cálido", "Ideal para estampar"],
    colors: ["Verde Bosque"],
    minQty: 10,
    weight: "280g",
    composition: "80% algodón · 20% poliéster",
    sizes: CANGURO_SIZES,
    sizeTable: CANGURO_SIZE_TABLE,
    priceWithPrint: CANGURO_PRICE_WITH,
    priceWithoutPrint: CANGURO_PRICE_WITHOUT,
  },
  {
    id: "canguro-oversize-beige",
    name: "Canguro Oversize Beige",
    category: "Canguros",
    priceFrom: 520,
    image: "/networkcapital/productos/canguro oversize beige.jpeg",
    description: "Canguro oversize en color beige. Corte amplio y moderno, ideal para estampados grandes.",
    features: ["Corte oversize", "Capucha", "Cálido", "Ideal para estampar"],
    colors: ["Beige"],
    minQty: 10,
    weight: "300g",
    composition: "80% algodón · 20% poliéster",
    sizes: CANGURO_SIZES,
    sizeTable: CANGURO_SIZE_TABLE,
    priceWithPrint: CANGURO_PRICE_WITH,
    priceWithoutPrint: CANGURO_PRICE_WITHOUT,
  },
  {
    id: "canguro-oversize-negro",
    name: "Canguro Oversize Negro",
    category: "Canguros",
    priceFrom: 520,
    image: "/networkcapital/productos/cangruo oversize negro.jpeg",
    description: "Canguro oversize en color negro. Corte amplio y moderno, ideal para estampados grandes.",
    features: ["Corte oversize", "Capucha", "Cálido", "Ideal para estampar"],
    colors: ["Negro"],
    minQty: 10,
    weight: "300g",
    composition: "80% algodón · 20% poliéster",
    sizes: CANGURO_SIZES,
    sizeTable: CANGURO_SIZE_TABLE,
    priceWithPrint: CANGURO_PRICE_WITH,
    priceWithoutPrint: CANGURO_PRICE_WITHOUT,
  },
  {
    id: "canguro-oversize-stone-wash",
    name: "Canguro Oversize Stone Wash",
    category: "Canguros",
    priceFrom: 520,
    image: "/networkcapital/productos/canguro oversize stone wash.jpeg",
    description: "Canguro oversize stone wash. Corte amplio y moderno, ideal para estampados grandes.",
    features: ["Corte oversize", "Stone wash", "Capucha", "Ideal para estampar"],
    colors: ["Stone Wash"],
    minQty: 10,
    weight: "300g",
    composition: "80% algodón · 20% poliéster",
    sizes: CANGURO_SIZES,
    sizeTable: CANGURO_SIZE_TABLE,
    priceWithPrint: CANGURO_PRICE_WITH,
    priceWithoutPrint: CANGURO_PRICE_WITHOUT,
  },
  {
    id: "canguro-con-cierre-azul",
    name: "Canguro con Cierre Azul",
    category: "Canguros",
    priceFrom: 540,
    image: "/networkcapital/productos/canguro con cierre azul.jpeg",
    description: "Canguro con cierre en color azul. Práctico, cálido y perfecto para personalizar con estampado.",
    features: ["Cierre completo", "Capucha", "Bolsillos", "Ideal para estampar"],
    colors: ["Azul"],
    minQty: 10,
    weight: "320g",
    composition: "80% algodón · 20% poliéster",
    sizes: CANGURO_SIZES,
    sizeTable: CANGURO_SIZE_TABLE,
    priceWithPrint: CANGURO_PRICE_WITH,
    priceWithoutPrint: CANGURO_PRICE_WITHOUT,
  },
];
